### ISSUE TITLE
Could not find class ::barbecue

### ISSUE THREAD

**Issue by ltutar** [pulling-strings/puppet-gitblit#2]
When backup parameter is set to true, I get the error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not find class ::barbecue for puppetagent1.home at /etc/puppetlabs/code/environments/production/modules/gitblit/manifests/backup.pp:12:3 on node puppetagent1.home

I set the backup parameter to false. I did not yet search for a solution.

**Comment by narkisr** [comment]
This is the [module](https://github.com/pulling-strings/puppet-barbecue), ill take a look and see if I can avoid requiring it when backup is set to false

**Comment by ltutar** [comment]
If backup is set to false, it is not required.

**Comment by narkisr** [comment]
Ok, the backup class defines a backup job to s3 and is optional (it will only work on Ubuntu any case)
