### ISSUE TITLE
Could not find declared class jdk

### ISSUE THREAD

**Issue by ltutar** [pulling-strings/puppet-gitblit#3]
I get the following error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class jdk at /etc/puppetlabs/code/environments/production/modules/gitblit/manifests/init.pp:16:3 on node puppetagent1.home

**Comment by narkisr** [comment]
This is the [jdk](https://github.com/pulling-strings/puppet-jdk) module,
