### ISSUE TITLE
Execution of '/bin/systemctl start gitblit' returned 1

### ISSUE THREAD

**Issue by ltutar** [pulling-strings/puppet-gitblit#4]
After installing jdk manually and removing it from the code, I get the following error:
Info: /Stage[main]/Gitblit::Config/Editfile::Config[repo folder]/Editfile[repo folder]: Scheduling refresh of Service[gitblit]
Error: Could not start Service[gitblit]: Execution of '/bin/systemctl start gitblit' returned 1: Job for gitblit.service failed. See 'systemctl status gitblit.service' and 'journalctl -xn' for details.
Error: /Stage[main]/Gitblit/Service[gitblit]/ensure: change from stopped to running failed: Could not start Service[gitblit]: Execution of '/bin/systemctl start gitblit' returned 1: Job for gitblit.service failed. See 'systemctl status gitblit.service' and 'journalctl -xn' for details.

I am installing gitblit on CentOS 7.

[root@puppetagent1 ~]# systemctl status gitblit.service
gitblit.service
   Loaded: loaded (/etc/rc.d/init.d/gitblit)
   Active: failed (Result: exit-code) since Wed 2015-10-21 11:06:18 CEST; 23s ago
  Process: 14726 ExecStart=/etc/rc.d/init.d/gitblit start (code=exited, status=1/FAILURE)

Oct 21 11:06:18 puppetagent1.home systemd[1]: Starting gitblit.service...
Oct 21 11:06:18 puppetagent1.home gitblit[14726]: /etc/rc.d/init.d/gitblit: line 10: /lib/lsb/init-functions: No such file or directory
Oct 21 11:06:18 puppetagent1.home systemd[1]: gitblit.service: control process exited, code=exited status=1
Oct 21 11:06:18 puppetagent1.home systemd[1]: Failed to start gitblit.service.
Oct 21 11:06:18 puppetagent1.home systemd[1]: Unit gitblit.service entered failed state.
[root@puppetagent1 ~]#

**Comment by narkisr** [comment]
Currently the module uses an init.d [script](https://github.com/pulling-strings/puppet-gitblit/blob/master/files/gitblit) (not systemd or upstart for that matter), 

This module was written for Ubuntu 14.x and will be ported to Ubuntu 15.x eventually, if youd like to add support for Centos variants in the [parent](https://github.com/opskeleton/gitblit-sandbox) project ill be happy to corporate on it.

**Comment by ltutar** [comment]
Hi Ronen,
I could get https://github.com/mgruener/puppet-gitblit running for CentOS with one modification. I'll give this module a try first.

Thank you for your quick responses.

**Comment by narkisr** [comment]
Cool
